# Spring
spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/department/**

# Server configuration
server:
  port: 8060

# Eureka server configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    initial-instance-info-replication-interval-seconds: 40

# Zipkin configuration
management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    com.netflix.discovery: DEBUG
