# Spring
spring:
  application:
    name: config-server
# profile
  profiles:
    active: native

# Server configuration
server:
  port: 8088

logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka.server: DEBUG
